version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./data:/app/data   # DB dumps, uploads
    ports:
      - "8077:8080"

  web:
    build: ./web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8077
    ports:
      - "3000:3000"

volumes:
  pgdata:
